### ISSUE TITLE
Flask Service

### ISSUE THREAD

**Issue by Castau** [Hold-Krykke/PythonExam#5]
* Hertil kunne man gøre brug af Twitters avancerede søgefunktioner, som at sortere efter popularitet, seneste, med/uden billeder. Eller søgning med/uden diverse ord, engagement, timeframes mm.  

[Notebook guide on Flask and how to deploy Flask](https://github.com/datsoftlyngby/dat4sem2020spring-python/blob/master/notebooks/08-2%20Web%20services.ipynb)

TASKS 
* [x] opret endpoint der kan modtage et input i form af hashtags og returnere præsentationen
  * [x] udvid til at kunne modtage flere hashtags
* ~~Lav evt en basal gui~~

**Comment by Castau** [comment]
In case you don't see it on discord, this #10 should fix the problem you had with my file :)

**Comment by MrHardcode** [comment]
We will not deploy the server. The server has a single endpoint and this endpoint returns different data (plot as png or JSON stats) depending on the information received in the request body. 
Check out #13 for more information
